FORMAT: 1A
HOST: https://ops-brizo.gentux.com/api/v1

# Brizo

# Group Access Tokens

Authentication is verified in two ways within Brizo: JWT authentication and access tokens.
You should always use an access token when interacting directly with the API.


JWT authentication is reserved for authentication via the web interface.

## Access Tokens [/access-tokens]

### List of All Access Tokens [GET]

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            [
              {
                "id": "1",
                "created_at": "2017-02-27T18:04:39Z",
                "updated_at": "2017-02-27T18:04:39Z",
                "token": "DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl"
              }
            ]

### Create a New Access Token [POST]

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 201 (application/json)

    + Body

            [
              {
                "id": "2",
                "created_at": "2017-02-27T18:04:39Z",
                "updated_at": "2017-02-27T18:04:39Z",
                "token": "HOR81CK8JA7MxHrKerdNMXKwFQuNNSJOPGVIl9cm0nBk9Oa0etPnPXdsSSDTfXHlwO9arN9vH4vfy8qqK8sxTVRajZC4q7eYCLMjMFtYLrsjouPEsgmxaWtAv1nCFtCe"
              }
            ]

# Group Users & Invites

## User [/users]

### Create a New User [POST]

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

    + Body

              {
                "username": "octocat"
              }

+ Response 201 (application/json)

## Invite List [/users/invites]

### List of All Invites [GET]

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            [
              {
                "id": "1",
                "created_at": "2017-02-27T15:36:48Z",
                "updated_at": "2017-02-27T15:36:48Z",
                "username": "octocat",
                "name": "The Octocat",
                "email": "octocat@github.com",
                "github_username": "octocat",
                "github_token": ""
              }
            ]

## Invite [/users/invites/{invite_id}]

### Delete an Invite [DELETE]

+ Parameters

    + invite_id: `1` (required, number) - ID of the Invite as an integer

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 204 (application/json)

# Group Applications

## Application List [/applications]

### List of All Applications [GET]

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            [
              {
                "id": "1",
                "created_at": "2017-02-24T18:59:41Z",
                "updated_at": "2017-02-24T18:59:41Z",
                "uuid": "cfae5919-2fb4-4e34-934a-30b310248295",
                "name": "My Application",
                "slug": "my-application",
                "environments": [
                  ...
                ]
              }
            ]

### Create a New Application [POST]

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

    + Body

              {
                "name": "My Application"
              }

+ Response 201 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-24T18:59:41Z",
              "updated_at": "2017-02-24T18:59:41Z",
              "uuid": "cfae5919-2fb4-4e34-934a-30b310248295",
              "name": "My Application",
              "slug": "my-application",
              "environments": [
                ...
              ]
            }

## Application [/applications/{application_id}]

### Get a Single Application [GET]

+ Parameters

    + application_id: `cfae5919-2fb4-4e34-934a-30b310248295` (required, uuid) - ID of the Application as a UUID

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-24T18:59:41Z",
              "updated_at": "2017-02-24T18:59:41Z",
              "uuid": "cfae5919-2fb4-4e34-934a-30b310248295",
              "name": "My Application",
              "slug": "my-application",
              "environments": [
                ...
              ]
            }

### Update a Single Application [PATCH]

::: warning
The `id` field of response body will be deprecated in future versions.
:::

+ Parameters

    + application_id: `cfae5919-2fb4-4e34-934a-30b310248295` (required, uuid) - ID of the Application as a UUID

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl
    + Body

            {
              "name": "My Updated Application"
            }

+ Response 200 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-24T18:59:41Z",
              "updated_at": "2017-02-25T19:06:41Z",
              "uuid": "cfae5919-2fb4-4e34-934a-30b310248295",
              "name": "My Updated Application",
              "slug": "my-updated-application",
              "environments": [
                ...
              ]
            }

# Group Environments

## Environment List [/environments]

### List of All Environments [GET]

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            [
              {
                "id": "1",
                "created_at": "2017-02-24T19:02:29Z",
                "updated_at": "2017-02-24T19:02:29Z",
                "uuid": "ac7c1cfd-1146-4ef3-aa37-62830af86a43",
                "name": "My Environment",
                "slug": "my-environment",
                "application_id": "1",
                "application": {
                  ...
                }
              }
            ]

### Create a New Environment [POST]

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

    + Body

              {
                "name": "My Environment"
              }

+ Response 201 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-24T19:02:29Z",
              "updated_at": "2017-02-24T19:02:29Z",
              "uuid": "ac7c1cfd-1146-4ef3-aa37-62830af86a43",
              "name": "My Environment",
              "slug": "my-environment",
              "application_id": "1",
              "application": {
                ...
              }
            }

## Environment [/environments/{environment_id}]

### Get a Single Environment [GET]

+ Parameters

    + environment_id: `ac7c1cfd-1146-4ef3-aa37-62830af86a43` (required, uuid) - ID of the Environment as a UUID

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-24T19:02:29Z",
              "updated_at": "2017-02-24T19:02:29Z",
              "uuid": "ac7c1cfd-1146-4ef3-aa37-62830af86a43",
              "name": "My Environment",
              "slug": "my-environment",
              "application_id": "1",
              "application": {
                ...
              }
            }

### Update a Single Environment [PATCH]

::: warning
The `id` field of response body will be deprecated in future versions.
:::

+ Parameters

    + environment_id: `ac7c1cfd-1146-4ef3-aa37-62830af86a43` (required, uuid) - ID of the Environment as a UUID

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl
    + Body

            {
              "name": "My Updated Environment"
            }

+ Response 200 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-24T19:02:29Z",
              "updated_at": "2017-02-25T19:06:41Z",
              "uuid": "ac7c1cfd-1146-4ef3-aa37-62830af86a43",
              "name": "My Updated Environment",
              "slug": "my-updated-environment",
              "application_id": "1",
              "application": {
                ...
              }
            }

# Group Versions

## Versions List [/environments/{environment_id}/versions]

### List of All Versions for an Environment [GET]

+ Parameters

    + environment_id: `ac7c1cfd-1146-4ef3-aa37-62830af86a43` (required, uuid) - ID of the Version's Environment as a UUID

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            [
              {
                "id": "1",
                "created_at": "2017-02-27T15:51:02Z",
                "updated_at": "2017-02-28T14:58:56Z",
                "uuid": "936e9ef6-4eeb-4eed-8869-4468b847d6ea",
                "name": "v1.0.0",
                "slug": "v1-0-0",
                "replicas": 5,
                "environment_id": 1,
                "environment": {
                  ...
                },
                "volumes": null,
                "containers": null
              }
            ]

### Create a New Version [POST]

+ Request (application/json)

    + Parameters

        + environment_id: `ac7c1cfd-1146-4ef3-aa37-62830af86a43` (required, uuid) - ID of the Version's Environment as a UUID

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

    + Body

            {
              "name": "My Version",
              "replicas": "5",
              "containers": [],
              "volumes": []
            }

+ Response 201 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-27T15:51:02Z",
              "updated_at": "2017-02-28T14:58:56Z",
              "uuid": "936e9ef6-4eeb-4eed-8869-4468b847d6ea",
              "name": "v1.0.0",
              "slug": "v1-0-0",
              "replicas": 5,
              "environment_id": 1,
              "environment": {
                ...
              },
              "volumes": null,
              "containers": null
            }

## Version [/environments/{environment_id}/versions/{version_id}]

### Get a Single Version [GET]

+ Parameters

    + environment_id: `ac7c1cfd-1146-4ef3-aa37-62830af86a43` (required, uuid) - ID of the Version's Environment as a UUID
    + version_id: `936e9ef6-4eeb-4eed-8869-4468b847d6ea` (required, uuid) - ID of the Version as a UUID

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-27T15:51:02Z",
              "updated_at": "2017-02-28T14:58:56Z",
              "uuid": "936e9ef6-4eeb-4eed-8869-4468b847d6ea",
              "name": "v1.0.0",
              "slug": "v1-0-0",
              "replicas": 5,
              "environment_id": 1,
              "environment": {
                ...
              },
              "volumes": null,
              "containers": null
            }

# Group Environment Configurations

## Environment Configurations List [/environments/{environment_id}/configuration]

### List of All Environment Configurations for an Environment [GET]

+ Parameters

    + environment_id: `ac7c1cfd-1146-4ef3-aa37-62830af86a43` (required, uuid) - ID of the Environment Configuration's Environment as a UUID

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 200 (application/json)

    + Body

            [
              {
                "id": "1",
                "created_at": "2017-02-27T15:44:00Z",
                "updated_at": "2017-02-27T15:44:00Z",
                "name": "MY_ENVIRONMENT_KEY",
                "value": "my_value",
                "environment_uuid": "ac7c1cfd-1146-4ef3-aa37-62830af86a43",
                "environment": {
                  ...
                }
              }
            ]

### Create a New Environment Configuration [POST]

+ Request (application/json)

    + Parameters

        + environment_id: `ac7c1cfd-1146-4ef3-aa37-62830af86a43` (required, uuid) - ID of the Environment Configuration's Environment as a UUID

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

    + Body

            {
              "name": "MY_ENVIRONMENT_KEY",
              "value": "my_value",
              "environment_uuid": "ac7c1cfd-1146-4ef3-aa37-62830af86a43"
            }

+ Response 201 (application/json)

    + Body

            {
              "id": "1",
              "created_at": "2017-02-27T15:44:00Z",
              "updated_at": "2017-02-27T15:44:00Z",
              "name": "MY_ENVIRONMENT_KEY",
              "value": "my_value",
              "environment_uuid": "ac7c1cfd-1146-4ef3-aa37-62830af86a43",
              "environment": {
                ...
              }
            }

## Environment Configuration [/environments/{environment_id}/configuration/{configuration_id}]

### Delete an Environment Configuration [DELETE]

+ Parameters

    + environment_id: `ac7c1cfd-1146-4ef3-aa37-62830af86a43` (required, uuid) - ID of the Environment Configuration's Environment as a UUID
    + configuration_id: `1` (required, number) - ID of the Environment Configuration as an integer

+ Request (application/json)

    + Headers

            Auth: Bearer DkfPUfxjydduam8HIRq5Za1uD8PBOdYLhTrGsXbMIuox5JTwfLFe1N0dZecs2gbnoN3le3D7z7MQKVvhydCVQzNqZnLjtARd3g643cX1Mn7rtuFLw1mkOHI2d0GFf5Cl

+ Response 204 (application/json)
